# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [ ]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, delimiter='\t')
print(chipo.head())

   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl

                                  choice_description item_price
0                                                NaN     $2.39
1                                       [Clementine]     $3.39
2                                            [Apple]     $3.39
3                                                NaN     $2.39
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

### Step 4. See the first 10 entries

In [ ]:
print(chipo.head(10))

   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl
5         3         1                           Chicken Bowl
6         3         1                          Side of Chips
7         4         1                          Steak Burrito
8         4         1                       Steak Soft Tacos
9         5         1                          Steak Burrito

                                  choice_description item_price
0                                                NaN     $2.39
1                                       [Clementine]     $3.39
2                                            [Apple]     $3.39
3                                                NaN     $2.39
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98
6                                                NaN     $1.69
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

### Step 5. What is the number of observations in the dataset?

In [ ]:
#number of observations
num_observations = chipo.shape[0]
print("Number of observations in the dataset:", num_observations)

Number of observations in the dataset: 4622

In [ ]:
#show info about the data
print(chipo.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB
None

### Step 6. What is the number of columns in the dataset?

In [ ]:
num_columns = chipo.shape[1]
print("Number of columns in the dataset:", num_columns)

Number of columns in the dataset: 5

### Step 7. Print the name of all the columns.

In [ ]:
print(chipo.columns)

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [ ]:
print(chipo.index)

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [ ]:
MOI = chipo.groupby('item_name')['quantity'].sum().idxmax()
print("Most-ordered item:", MOI)

Most-ordered item: Chicken Bowl

### Step 10. For the most-ordered item, how many items were ordered?

In [ ]:
quantity_ordered = chipo.groupby('item_name')['quantity'].sum().max()
print("Number of items ordered for the most-ordered item:", quantity_ordered)

Number of items ordered for the most-ordered item: 761

### Step 11. What was the most ordered item in the choice_description column?

In [ ]:
most_ordered_choice = chipo.groupby('choice_description')['quantity'].sum().idxmax()
print("Most ordered item in the choice_description column:", most_ordered_choice)

Most ordered item in the choice_description column: [Diet Coke]

### Step 12. How many items were orderd in total?

In [ ]:
total_items_ordered = chipo['quantity'].sum()
print("Total number of items ordered:", total_items_ordered)

Total number of items ordered: 4972

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [ ]:
print("Type of item price before conversion:", chipo['item_price'].dtype)

Type of item price before conversion: object

#### Step 13.b. Create a lambda function and change the type of item price

In [ ]:
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x[1:]))

#### Step 13.c. Check the item price type

In [ ]:
print("Type of item price after conversion:", chipo['item_price'].dtype)

Type of item price after conversion: float64

### Step 14. How much was the revenue for the period in the dataset?

In [ ]:
revenue = (chipo['quantity'] * chipo['item_price']).sum()
print("Revenue for the period:", revenue)

Revenue for the period: 39237.02

### Step 15. How many orders were made in the period?

In [ ]:
num_orders = chipo['order_id'].nunique()
print("Number of orders made in the period:", num_orders)

Number of orders made in the period: 1834

### Step 16. What is the average revenue amount per order?

In [ ]:
average_revenue_per_order = revenue / num_orders

In [ ]:
print("Average revenue amount per order:", average_revenue_per_order)

Average revenue amount per order: 21.39423118865867

### Step 17. How many different items are sold?

In [ ]:
num_different_items = chipo['item_name'].nunique()

In [ ]:
print("Number of different items sold:", num_different_items)

Number of different items sold: 50