# Ex - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

### Step 3. Assign it to a variable called drinks.

In [ ]:
dataset = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv"
drinks = pd.read_csv(dataset)

### Step 4. Which continent drinks more beer on average?

In [ ]:
beer_avg = drinks.groupby('continent')['beer_servings'].mean()
continent_most_beer = beer_avg.idxmax()
print(f"The continent that drinks the most beer on average is {continent_most_beer}")

The continent that drinks the most beer on average is EU

### Step 5. For each continent print the statistics for wine consumption.

In [ ]:
wine = drinks.groupby('continent')['wine_servings'].describe()
print("\nStatistics for wine consumption by continent:")
print(wine)

Statistics for wine consumption by continent:
           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

### Step 6. Print the mean alcohol consumption per continent for every column

In [ ]:
print(drinks.dtypes)
numeric_columns = ['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']
drinks[numeric_columns] = drinks[numeric_columns].apply(pd.to_numeric, errors='coerce')
try:
    alcohol_means = drinks.groupby('continent').mean()
    print("\nMean alcohol consumption per continent for every column:")
    print(alcohol_means)
except Exception as e:
    print(f"Error occurred: {e}")

country                          object
beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object
Error occurred: Could not convert AlgeriaAngolaBeninBotswanaBurkina FasoBurundiCote d'IvoireCabo VerdeCameroonCentral African RepublicChadComorosCongoDR CongoDjiboutiEgyptEquatorial GuineaEritreaEthiopiaGabonGambiaGhanaGuineaGuinea-BissauKenyaLesothoLiberiaLibyaMadagascarMalawiMaliMauritaniaMauritiusMoroccoMozambiqueNamibiaNigerNigeriaRwandaSao Tome & PrincipeSenegalSeychellesSierra LeoneSomaliaSouth AfricaSudanSwazilandTogoTunisiaUgandaTanzaniaZambiaZimbabwe to numeric

### Step 7. Print the median alcohol consumption per continent for every column

In [ ]:
print(drinks.dtypes)
numeric_columns = ['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']
drinks[numeric_columns] = drinks[numeric_columns].apply(pd.to_numeric, errors='coerce')
try:
    alcohol_medians = drinks.groupby('continent').median()
    print("\nMean alcohol consumption per continent for every column:")
    print(alcohol_medians)
except Exception as e:
    print(f"Error occurred: {e}")

country                          object
beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object
Error occurred: could not convert string to float: 'Algeria'

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [ ]:
drinks['spirit_servings'] = pd.to_numeric(drinks['spirit_servings'], errors='coerce')
drinks.dropna(subset=['spirit_servings'], inplace=True)

spirit_stats = drinks.groupby('continent')['spirit_servings'].agg(['mean', 'min', 'max'])
spirit_stats_df = pd.DataFrame(spirit_stats)

print("Mean, min, and max values for spirit consumption:")
print(spirit_stats_df)

Mean, min, and max values for spirit consumption:
                 mean  min  max
continent
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302